### ISSUE TITLE
Winleafs does not start

### ISSUE THREAD

**Issue by StijnOostdam** [winleafs/Winleafs#107]
https://old.reddit.com/r/Nanoleaf/comments/eo8d49/winleafs_10_a_windows_application_for_your/fea83f0/

- No logs
- No logs in Windows Event viewer other than successful installation
- Does not get flagged by anti virus

**Comment by StijnOostdam** [comment]
[Setup.zip](https://github.com/winleafs/Winleafs/files/4055675/Setup.zip)

**Comment by ScottBeeson** [comment]
Installed latest .NET runtime and it did not help. Then tried the attached installer above, same result. No WinLeafs folder created in c:/users/<username>/AppData/Roaming

When I launch the installer I get a UAC prompt. After that a quick install window and then nothing.  When I launch the executable I get nothing.

**Comment by StijnOostdam** [comment]
@ScottBeeson Thanks for the update. Also no Winleafs folder in AppData/Local?

**Comment by StijnOostdam** [comment]
Other Reddit user just posted this:

Did it, and found this in the log:

&#x200B;

System.TypeLoadException: Could not load type 'Winleafs.Models.Models.Scheduling.Triggers.BaseEventTrigger' from assembly 'Winleafs.Models, Version=[1.0.0.0](https://1.0.0.0), Culture=neutral, PublicKeyToken=null'.

**Comment by StijnOostdam** [comment]
More logs: 
2020-01-13 16:56:17.9905|INFO|Winleafs.Wpf.Views.Setup.SetupWindow|Discovered following device: Nanoleaf-Aurora, IPs: System.Collections.Generic.List\`1\[System.Net.IPAddress\], Port: 16021

2020-01-13 16:57:02.0476|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request: Address: [http://192.168.1.2:16021/](http://192.168.1.2:16021/), URL: api/v1/lnMMdLgAUQxo5BhZki8eyrRkqiD1S5Oy/identify, Method: PUT, Body: 

2020-01-13 16:57:02.0944|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request: Address: [http://192.168.1.2:16021/](http://192.168.1.2:16021/), URL: api/v1/lnMMdLgAUQxo5BhZki8eyrRkqiD1S5Oy/effects/effectsList, Method: GET, Body: 

2020-01-13 16:57:20.9379|INFO|Winleafs.Wpf.Views.Setup.SetupWindow|Successfully added device Ben's NanoLeaf

2020-01-13 16:57:21.1407|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request: Address: [http://192.168.1.2:16021/](http://192.168.1.2:16021/), URL: api/v1/lnMMdLgAUQxo5BhZki8eyrRkqiD1S5Oy/panelLayout/layout, Method: GET, Body: 

2020-01-13 16:57:21.1919|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request: Address: [http://192.168.1.2:16021/](http://192.168.1.2:16021/), URL: api/v1/lnMMdLgAUQxo5BhZki8eyrRkqiD1S5Oy/panelLayout/globalOrientation, Method: GET, Body: 

2020-01-13 16:57:21.5195|FATAL|Winleafs.Wpf.Views.App|Unhandled exception occurred

System.TypeLoadException: Could not load type 'Winleafs.Models.Models.Scheduling.Triggers.BaseEventTrigger' from assembly 'Winleafs.Models, Version=[1.0.0.0](https://1.0.0.0), Culture=neutral, PublicKeyToken=null'.

   at Winleafs.Wpf.Api.Events.EventTriggersCollection..ctor(Orchestrator orchestrator)

   at Winleafs.Wpf.Api.Orchestrator..ctor(Device device)

   at Winleafs.Wpf.Api.OrchestratorCollection.AddOrchestratorForDevice(Device device)

   at Winleafs.Wpf.Api.OrchestratorCollection.Initialize()

   at Winleafs.Wpf.Views.App.NormalStartup(StartupEventArgs e)

   at Winleafs.Wpf.Views.Setup.SetupWindow.Finish\_Click(Object sender, RoutedEventArgs e)

   at Winleafs.Wpf.Views.Setup.NameDeviceControl.Finish\_Click(Object sender, RoutedEventArgs e)

   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)

   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)

   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)

   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)

   at System.Windows.Controls.Primitives.ButtonBase.OnClick()

   at System.Windows.Controls.Button.OnClick()

   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)

   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)

   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)

   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)

   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)

   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)

   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)

   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)

   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)

   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)

   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)

   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)

   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)

   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)

   at System.Windows.Input.InputManager.ProcessStagingArea()

   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)

   at System.Windows.Input.StylusWisp.WispLogic.PromoteMainToMouse(StagingAreaInputItem stagingItem)

   at System.Windows.Input.StylusWisp.WispLogic.PromoteMainUpToTouch(WispStylusDevice stylusDevice, StagingAreaInputItem stagingItem)

   at System.Windows.Input.StylusWisp.WispLogic.PromoteMainToTouch(ProcessInputEventArgs e, StylusEventArgs stylusEventArgs)

   at System.Windows.Input.StylusWisp.WispLogic.PromoteMainToOther(ProcessInputEventArgs e)

   at System.Windows.Input.StylusWisp.WispLogic.PostProcessInput(Object sender, ProcessInputEventArgs e)

   at System.Windows.Input.InputManager.RaiseProcessInputEventHandlers(ProcessInputEventHandler postProcessInput, ProcessInputEventArgs processInputEventArgs)

   at System.Windows.Input.InputManager.ProcessStagingArea()

   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)

   at System.Windows.Input.StylusWisp.WispLogic.InputManagerProcessInput(Object oInput)

   at System.Windows.Input.StylusWisp.WispLogic.PreProcessInput(Object sender, PreProcessInputEventArgs e)

   at System.Windows.Input.InputManager.ProcessStagingArea()

   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)

   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)

   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)

   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler) System.Object:

**Comment by bartdebever** [comment]
@ScottBeeson may I ask for what hardware and OS you are using?

**Comment by StijnOostdam** [comment]
Likely issue with .NET Core 3. We should revert back to framework. Do not forget to check if links and startup registry key still work

**Comment by bartdebever** [comment]
Issue has been identified as .NET Core 3 **SDK** needs to be installed for WPF application to run. Fix is being made in the [installer-v2 branch](https://github.com/winleafs/Winleafs/tree/installer-v2)

**Comment by ScottBeeson** [comment]
Nice!

**Comment by ScottBeeson** [comment]
Confirmed that having the SDK installed fixes the issue.

I was the original reporter on Reddit.

**Comment by bartdebever** [comment]
As we speak, we just got a build working as a self-contained application. We will pass a Setup/zip onto this issue as soon as we can. Please feel free to test this with your machine

**Comment by StijnOostdam** [comment]
We released an update, could you maybe test that?

**Comment by ScottBeeson** [comment]
Well, since I already installed the SDK manually this machine wouldn't be a great test.  I'll see if I have time to test it on my laptop or another machine.

**Comment by StijnOostdam** [comment]
Reddit users confirmed v1.0.1 as working, closing
