### ISSUE TITLE
v1.01 - Changing options on Screen Mirroring crashes out

### ISSUE THREAD

**Issue by Castlenock** [winleafs/Winleafs#109]
When hitting 'Save' in 'options' -> 'screen mirror', Winleafs crashes out with no error, upon restart no changes have taken effect.

Windows 10 / gaming build
2 monitors (actually 3 from windows stand point...)
2 Canvas installations earmarked with the program (haven't connected the other 5, will test with my one aurora install later...)

Tried on different monitors, installations, etc.  Most I can get is ambient default settings.

**Comment by bartdebever** [comment]
Would you be able to supply your logs located at %Appdata%/Winleafs/log.txt

**Comment by StijnOostdam** [comment]
@Castlenock Which setting did you change exactly? Monitor? Algorithm?

**Comment by Castlenock** [comment]
Hey all,

  Sorry this took me so long, haven't been at my home station where this runs on in a week...  I'm going to options and changing the algorithm from ambilight to *anything else* crashes shortly after save.  Logs follow, looks like it's finding a null when it expects a value...

2020-01-20 08:14:09.1356|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request: Address: http://192.168.1.27:16021/, URL: api/v1/olxqJBoQPH5jv3Q50EnsZoG5etMOKitB/panelLayout/layout, Method: GET, Body: 
2020-01-20 08:14:11.2553|WARN|Winleafs.Api.Endpoints.NanoleafEndpoint|Request failed, statuscode: 0 0, status description: , content: 
2020-01-20 08:14:11.2576|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request: Address: http://192.168.1.27:16021/, URL: api/v1/olxqJBoQPH5jv3Q50EnsZoG5etMOKitB/panelLayout/globalOrientation, Method: GET, Body: 
2020-01-20 08:14:13.2601|WARN|Winleafs.Api.Endpoints.NanoleafEndpoint|Request failed, statuscode: 0 0, status description: , content: 
2020-01-20 08:14:13.3133|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request: Address: http://192.168.1.41:16021/, URL: api/v1/yvb0UC6YLXfCyIa3TWgoAtW3QxmMy4By/panelLayout/layout, Method: GET, Body: 
2020-01-20 08:14:13.3133|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request: Address: http://192.168.1.27:16021/, URL: api/v1/olxqJBoQPH5jv3Q50EnsZoG5etMOKitB/state/on, Method: GET, Body: 
2020-01-20 08:14:15.3198|WARN|Winleafs.Api.Endpoints.NanoleafEndpoint|Request failed, statuscode: 0 0, status description: , content: 
2020-01-20 08:14:15.3271|WARN|Winleafs.Api.Endpoints.NanoleafEndpoint|Request failed, statuscode: 0 0, status description: , content: 
2020-01-20 08:14:15.3271|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request: Address: http://192.168.1.41:16021/, URL: api/v1/yvb0UC6YLXfCyIa3TWgoAtW3QxmMy4By/panelLayout/globalOrientation, Method: GET, Body: 
2020-01-20 08:14:17.3364|WARN|Winleafs.Api.Endpoints.NanoleafEndpoint|Request failed, statuscode: 0 0, status description: , content: 
2020-01-20 08:14:17.3364|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request: Address: http://192.168.1.41:16021/, URL: api/v1/yvb0UC6YLXfCyIa3TWgoAtW3QxmMy4By/state/on, Method: GET, Body: 
2020-01-20 08:14:17.6374|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request: Address: http://192.168.1.41:16021/, URL: api/v1/yvb0UC6YLXfCyIa3TWgoAtW3QxmMy4By/panelLayout/layout, Method: GET, Body: 
2020-01-20 08:14:19.3453|WARN|Winleafs.Api.Endpoints.NanoleafEndpoint|Request failed, statuscode: 0 0, status description: , content: 
2020-01-20 08:14:19.6518|WARN|Winleafs.Api.Endpoints.NanoleafEndpoint|Request failed, statuscode: 0 0, status description: , content: 
2020-01-20 08:14:19.6518|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request: Address: http://192.168.1.41:16021/, URL: api/v1/yvb0UC6YLXfCyIa3TWgoAtW3QxmMy4By/panelLayout/globalOrientation, Method: GET, Body: 
2020-01-20 08:14:21.6677|WARN|Winleafs.Api.Endpoints.NanoleafEndpoint|Request failed, statuscode: 0 0, status description: , content: 
2020-01-20 08:14:21.9106|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request: Address: http://192.168.1.41:16021/, URL: api/v1/yvb0UC6YLXfCyIa3TWgoAtW3QxmMy4By/panelLayout/layout, Method: GET, Body: 
2020-01-20 08:14:23.9186|WARN|Winleafs.Api.Endpoints.NanoleafEndpoint|Request failed, statuscode: 0 0, status description: , content: 
2020-01-20 08:14:23.9186|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request: Address: http://192.168.1.41:16021/, URL: api/v1/yvb0UC6YLXfCyIa3TWgoAtW3QxmMy4By/panelLayout/globalOrientation, Method: GET, Body: 
2020-01-20 08:14:25.9212|WARN|Winleafs.Api.Endpoints.NanoleafEndpoint|Request failed, statuscode: 0 0, status description: , content: 
2020-01-20 08:15:25.2450|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request: Address: http://192.168.1.27:16021/, URL: api/v1/olxqJBoQPH5jv3Q50EnsZoG5etMOKitB/panelLayout/layout, Method: GET, Body: 
2020-01-20 08:15:27.3041|WARN|Winleafs.Api.Endpoints.NanoleafEndpoint|Request failed, statuscode: 0 0, status description: , content: 
2020-01-20 08:15:27.3063|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request: Address: http://192.168.1.27:16021/, URL: api/v1/olxqJBoQPH5jv3Q50EnsZoG5etMOKitB/panelLayout/globalOrientation, Method: GET, Body: 
2020-01-20 08:15:29.3211|WARN|Winleafs.Api.Endpoints.NanoleafEndpoint|Request failed, statuscode: 0 0, status description: , content: 
2020-01-20 08:15:29.3455|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request: Address: http://192.168.1.41:16021/, URL: api/v1/yvb0UC6YLXfCyIa3TWgoAtW3QxmMy4By/panelLayout/layout, Method: GET, Body: 
2020-01-20 08:15:29.3455|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request: Address: http://192.168.1.27:16021/, URL: api/v1/olxqJBoQPH5jv3Q50EnsZoG5etMOKitB/state/on, Method: GET, Body: 
2020-01-20 08:15:29.9400|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request: Address: http://192.168.1.41:16021/, URL: api/v1/yvb0UC6YLXfCyIa3TWgoAtW3QxmMy4By/panelLayout/globalOrientation, Method: GET, Body: 
2020-01-20 08:15:29.9663|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request: Address: http://192.168.1.41:16021/, URL: api/v1/yvb0UC6YLXfCyIa3TWgoAtW3QxmMy4By/state/on, Method: GET, Body: 
2020-01-20 08:15:29.9835|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request: Address: http://192.168.1.41:16021/, URL: api/v1/yvb0UC6YLXfCyIa3TWgoAtW3QxmMy4By/state, Method: PUT, Body: {"on": {"value":false}}
2020-01-20 08:15:30.0687|WARN|Winleafs.Api.Endpoints.NanoleafEndpoint|Request failed, statuscode: 204 NoContent, status description: No Content, content: 
2020-01-20 08:15:31.3499|WARN|Winleafs.Api.Endpoints.NanoleafEndpoint|Request failed, statuscode: 0 0, status description: , content: 
2020-01-20 08:15:56.4557|FATAL|Winleafs.Wpf.Views.App|Unhandled exception occurred
System.ArgumentNullException: Value cannot be null. (Parameter 'first')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Except[TSource](IEnumerable`1 first, IEnumerable`1 second)
   at Winleafs.Wpf.Views.Options.OptionsWindow.Save_Click(Object sender, RoutedEventArgs e) in C:\Users\easy_\source\repos\winleafs\Winleafs\Winleafs.Wpf\Views\Options\OptionsWindow.xaml.cs:line 134
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler) System.Object:

**Comment by StijnOostdam** [comment]
Thanks for the logs! We just released a new version, which should fix your issue (https://github.com/winleafs/Winleafs/releases/tag/v1.0.3). If its not the case, please re-open this issue.
