### ISSUE TITLE
Saving settings crashes v1.0.2

### ISSUE THREAD

**Issue by EsDeKa** [winleafs/Winleafs#114]
**Describe the bug**
Just installed the application to play around with it, but having some issues with crashes. Pairing seemed to work fine, but saving settings or choosing the Screen mirror effect crashes the app instantly. Not sure if it's the same issue as #109 so I made a new one.

Win10 + Nanoleaf Light Panels 3.3.3

**To Reproduce**
1. Open options
2. Click save (even without changing anything)
3. Crash

Another crash
1. Select Winleafs - Screen Mirror
2. Crash

**Logs**
[log.log](https://github.com/winleafs/Winleafs/files/4084464/log.log)
[Settings.txt](https://github.com/winleafs/Winleafs/files/4084465/Settings.txt)

The settings crash seems to generate this stack:
```
System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.ContainsKey(TKey key)
   at Winleafs.Wpf.Api.Effects.CustomEffectsCollection.EffectIsCustomEffect(String effectName) in C:\Users\easy_\source\repos\winleafs\Winleafs\Winleafs.Wpf\Api\Effects\CustomEffectsCollection.cs:line 54
   at Winleafs.Wpf.Api.Orchestrator.ActivateEffect(String effectName, Int32 brightness) in C:\Users\easy_\source\repos\winleafs\Winleafs\Winleafs.Wpf\Api\Orchestrator.cs:line 120
```

Starting screen mirroring doesn't seem to log an error, this is from setting a working effect, then switching to screen mirror:

```
2020-01-20 06:00:31.5436|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request: Address: http://10.10.10.7:16021/, URL: api/v1/ubCrc6ddK5esDJFcOx8tKpxaHIHxftDo/state, Method: PUT, Body: {"brightness": {"value":0}}
2020-01-20 06:00:31.6529|WARN|Winleafs.Api.Endpoints.NanoleafEndpoint|Request failed, statuscode: 204 NoContent, status description: No Content, content: 
2020-01-20 06:00:31.6529|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request: Address: http://10.10.10.7:16021/, URL: api/v1/ubCrc6ddK5esDJFcOx8tKpxaHIHxftDo/effects, Method: PUT, Body: {"select": "Inner Peace"}
2020-01-20 06:00:31.9158|WARN|Winleafs.Api.Endpoints.NanoleafEndpoint|Request failed, statuscode: 204 NoContent, status description: No Content, content: 
2020-01-20 06:00:41.6184|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request: Address: http://10.10.10.7:16021/, URL: api/v1/ubCrc6ddK5esDJFcOx8tKpxaHIHxftDo/state, Method: PUT, Body: {"brightness": {"value":0}}
2020-01-20 06:00:41.6960|WARN|Winleafs.Api.Endpoints.NanoleafEndpoint|Request failed, statuscode: 204 NoContent, status description: No Content, content: 
```

**Comment by StijnOostdam** [comment]
Hey, thanks for the extensive description! I will fix this later today and release an update. Meanwhile, you could try adding a custom color before saving your settings and see if that helps.

**Comment by StijnOostdam** [comment]
We just released a new version: https://github.com/winleafs/Winleafs/releases/tag/v1.0.3, which should fix this issue. Please re-open if that is not the case.
