### ISSUE TITLE
Crashing on Startup

### ISSUE THREAD

**Issue by Helifano** [winleafs/Winleafs#148]
**Describe the bug**
It was working previously, but now when I try to launch the program (v1.1.4) it never fully starts up. The icon shows up in my notification tray, but then soon disappears. No luck trying to run as administrator. Seems like it could be having trouble connecting to the panels, but if that is the case, I can't get into the software to reconnect them.

**Logs**
https://pastebin.com/KsG31w9V

**Comment by StijnOostdam** [comment]
Het, thanks for the report. I should be able to fix the error fairly easily. Out of curiosity, our app detects your device type as "Unknown". What is your exact setup? Type and number of panels.

Exception log:
````
2020-10-06 05:27:56.9574|FATAL|Winleafs.Wpf.Views.App|Unhandled exception occurred
System.NotImplementedException: No icon implemented for device type Unknown
   at Winleafs.Wpf.Views.MainWindows.DeviceUserControl..ctor(Device device, MainWindow parent) in C:\Users\easy_\source\repos\winleafs\Winleafs\Winleafs.Wpf\Views\MainWindows\DeviceUserControl.xaml.cs:line 73
   at Winleafs.Wpf.Views.MainWindows.TaskbarIcon.SelectedDeviceChanged() in C:\Users\easy_\source\repos\winleafs\Winleafs\Winleafs.Wpf\Views\MainWindows\TaskbarIcon.xaml.cs:line 67
   at Winleafs.Wpf.Views.MainWindows.TaskbarIcon.set_SelectedDevice(String value) in C:\Users\easy_\source\repos\winleafs\Winleafs\Winleafs.Wpf\Views\MainWindows\TaskbarIcon.xaml.cs:line 31
   at Winleafs.Wpf.Views.MainWindows.TaskbarIcon.Initialize(MainWindow mainWindow) in C:\Users\easy_\source\repos\winleafs\Winleafs\Winleafs.Wpf\Views\MainWindows\TaskbarIcon.xaml.cs:line 54
   at Winleafs.Wpf.Views.MainWindows.MainWindow..ctor() in C:\Users\easy_\source\repos\winleafs\Winleafs\Winleafs.Wpf\Views\MainWindows\MainWindow.xaml.cs:line 77
   at Winleafs.Wpf.Views.App.NormalStartup(StartupEventArgs startupEventArgs) in C:\Users\easy_\source\repos\winleafs\Winleafs\Winleafs.Wpf\Views\App.xaml.cs:line 108
   at Winleafs.Wpf.Views.App.App_Startup(Object sender, StartupEventArgs e) in C:\Users\easy_\source\repos\winleafs\Winleafs\Winleafs.Wpf\Views\App.xaml.cs:line 73
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
````

**Comment by Helifano** [comment]
15 of the triangular rhythm panels, though I never use the rhythm functionality.

**Comment by StijnOostdam** [comment]
Hmmm could you maybe send us your settings file? It is in the same location as the logs

**Comment by StijnOostdam** [comment]
@bartdebever This bug needs two fixes:
- Application should not crash if the device type is unknown, we probably should display a ? in the GUI to indicate the unknown device type plus do not draw any panels.
- @Helifano 's device should not be recognized as Unknown

**Comment by Helifano** [comment]
I replaced the location data with "###" as best I could find for obvious security reasons, but here is the file paste

https://pastebin.com/b92rRggM

**Comment by StijnOostdam** [comment]
@Helifano I just published v1.1.5 that fixes your crash: https://github.com/winleafs/Winleafs/releases/tag/v1.1.5

The reason Winleafs does not know what type of panels you have, is because the request of the panel layout fails, hence it defaults to unknown. Could you tell us which version of the panel software you are running? This is visible in the Nanoleaf app.

**Comment by Helifano** [comment]
@StijnOostdam I am not exactly sure what you mean; I do not run any accompanying Nanoleaf app. The Winleafs program is all I use. I did connect the Nanoleafs to the mobile app once before discovering Winleafs. The system page in the Nanoleaf mobile app says my panels are model number NL22 and Firmware version 3.3.4, if that is helpful at all.

**Comment by Helifano** [comment]
And thank you and all involved for your efforts on this program!

**Comment by StijnOostdam** [comment]
> The system page in the Nanoleaf mobile app says my panels are model number NL22 and Firmware version 3.3.4, if that is helpful at all.

Thanks, that was I was looking for.

> And thank you and all involved for your efforts on this program!

You are welcome! Glad to hear you like it.
