### ISSUE TITLE
Unknown Error when connecting to spotify

### ISSUE THREAD

**Issue by brandon-chung** [winleafs/Winleafs#202]
**Describe the bug**
I don't see an button to connect to spotify in the Options menu. It just says `Unknown error when trying to connect with Spotify. Please report to the developers.`

**To Reproduce**
3. Crash

**Logs**
```
2021-11-24 19:17:33.3117|ERROR|Winleafs.Wpf.Views.Options.OptionsWindow|Unknown error when trying to connect to Spotify
Winleafs.Server.Exceptions.WinleafsServerException: Error during request to Winleafs server
   at Winleafs.Server.Endpoints.WinleafsServerEndpoint.SendRequest(String endpoint, Method method, Type returnType, Object body, Boolean disableLogging) in C:\Users\easy_\source\repos\winleafs\Winleafs\Winleafs.Server\Endpoints\WinleafsServerEndpoint.cs:line 122
   at Winleafs.Server.Endpoints.WinleafsServerEndpoint.SendRequest[T](String endpoint, Method method, Object body) in C:\Users\easy_\source\repos\winleafs\Winleafs\Winleafs.Server\Endpoints\WinleafsServerEndpoint.cs:line 43
   at Winleafs.Server.Endpoints.SpotifyEndpoint.IsConnected() in C:\Users\easy_\source\repos\winleafs\Winleafs\Winleafs.Server\Endpoints\SpotifyEndpoint.cs:line 36
   at Winleafs.Wpf.Views.Options.OptionsWindow.InitializeSpotifyButtons() in C:\Users\easy_\source\repos\winleafs\Winleafs\Winleafs.Wpf\Views\Options\OptionsWindow.xaml.cs:line 437
```

**Screenshots**
https://i.imgur.com/VyDFajv.png

**Additional context**

**Comment by bartdebever** [comment]
Hey there,

It seemed our server experienced an unexpected crash. I've since manually restarted it and it should be up and running again. Please check if your Spotify functionality works again.
