### ISSUE TITLE
Screen Mirror "Stretch" and "Fit" mode not working anymore

### ISSUE THREAD

**Issue by AoKoori** [winleafs/Winleafs#220]
**Describe the bug**
hello, so when i was on windows 10 everything was working perfectly but since i updated to windows 11, the "Stretch" and "Fit" mode 
option for the screen mirror effect don't wok anymore

**To Reproduce**
1. Go to 'Options'
2. Click on 'Screen Mirror' tab
3. Select "Stretch" or "Fit" mode
4. restart winleaf to update the screen mirror option
5. Select the screen mirror effect
6. Nanoleafs don't light up

**Logs**
2023-09-05 13:14:46.1423|INFO|Winleafs.Server.Endpoints.WinleafsServerEndpoint|Sending following request Winleafs Server: Address: https://api.winleafs.com/, URL: /spotify/is-connected/5d3ff693-4894-45ea-bebf-ed1c2e557289, Method: GET, Body: 
2023-09-05 13:14:48.1600|WARN|Winleafs.Server.Endpoints.WinleafsServerEndpoint|Winleafs server request failed, statuscode: 0 0, status description: , content: 
2023-09-05 13:14:48.1600|ERROR|Winleafs.Wpf.Views.Options.OptionsWindow|Unknown error when trying to connect to Spotify
Winleafs.Server.Exceptions.WinleafsServerException: Error during request to Winleafs server
   at Winleafs.Server.Endpoints.WinleafsServerEndpoint.SendRequest(String endpoint, Method method, Type returnType, Object body, Boolean disableLogging) in C:\Users\easy_\source\repos\winleafs\Winleafs\Winleafs.Server\Endpoints\WinleafsServerEndpoint.cs:line 120
   at Winleafs.Server.Endpoints.WinleafsServerEndpoint.SendRequest[T](String endpoint, Method method, Object body) in C:\Users\easy_\source\repos\winleafs\Winleafs\Winleafs.Server\Endpoints\WinleafsServerEndpoint.cs:line 43
   at Winleafs.Server.Endpoints.SpotifyEndpoint.IsConnected() in C:\Users\easy_\source\repos\winleafs\Winleafs\Winleafs.Server\Endpoints\SpotifyEndpoint.cs:line 36
   at Winleafs.Wpf.Views.Options.OptionsWindow.InitializeSpotifyButtons() in C:\Users\easy_\source\repos\winleafs\Winleafs\Winleafs.Wpf\Views\Options\OptionsWindow.xaml.cs:line 437
2023-09-05 13:15:01.4983|INFO|Winleafs.Wpf.Api.ScheduleTimer|Scheduler turning device 192.168.1.12 off
2023-09-05 13:15:01.5193|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request to Nanoleaf: Address: http://192.168.1.12:16021/, URL: api/v1/RebbMsWZs5KryF7Vm8sfRYHpcBxdh0yp/state/on, Method: GET, Body: 
2023-09-05 13:15:01.5193|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request to Nanoleaf: Address: http://192.168.1.12:16021/, URL: api/v1/RebbMsWZs5KryF7Vm8sfRYHpcBxdh0yp/panelLayout/layout, Method: GET, Body: 
2023-09-05 13:15:01.5193|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request to Nanoleaf: Address: http://192.168.1.12:16021/, URL: api/v1/RebbMsWZs5KryF7Vm8sfRYHpcBxdh0yp/panelLayout/globalOrientation, Method: GET, Body: 
2023-09-05 13:15:01.5466|INFO|Winleafs.Wpf.Api.ScheduleTimer|Scheduler turning device 192.168.1.12 off
2023-09-05 13:15:01.5466|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request to Nanoleaf: Address: http://192.168.1.12:16021/, URL: api/v1/RebbMsWZs5KryF7Vm8sfRYHpcBxdh0yp/state/on, Method: GET, Body: 
2023-09-05 13:15:04.3709|INFO|Winleafs.Wpf.Views.MainWindows.DeviceUserControl|User manually enabling effect Winleafs - Screen mirror with brightness 0 for device 192.168.1.12
2023-09-05 13:15:04.3709|INFO|Winleafs.Wpf.Api.Orchestrator|Orchestrator is activating effect Winleafs - Screen mirror with brightness 0 for device 192.168.1.12
2023-09-05 13:15:04.3709|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request to Nanoleaf: Address: http://192.168.1.12:16021/, URL: api/v1/RebbMsWZs5KryF7Vm8sfRYHpcBxdh0yp/state, Method: PUT, Body: { brightness = { value = 0 } }
2023-09-05 13:15:04.4265|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request to Nanoleaf: Address: http://192.168.1.12:16021/, URL: api/v1/RebbMsWZs5KryF7Vm8sfRYHpcBxdh0yp/effects, Method: PUT, Body: { write = { command = display, animType = extControl, extControlVersion = v2 } }
2023-09-05 13:18:54.4781|INFO|Winleafs.Server.Endpoints.WinleafsServerEndpoint|Sending following request Winleafs Server: Address: https://api.winleafs.com/, URL: /spotify/is-connected/5d3ff693-4894-45ea-bebf-ed1c2e557289, Method: GET, Body: 
2023-09-05 13:18:56.4821|WARN|Winleafs.Server.Endpoints.WinleafsServerEndpoint|Winleafs server request failed, statuscode: 0 0, status description: , content: 
2023-09-05 13:18:56.4821|ERROR|Winleafs.Wpf.Views.Options.OptionsWindow|Unknown error when trying to connect to Spotify
Winleafs.Server.Exceptions.WinleafsServerException: Error during request to Winleafs server
   at Winleafs.Server.Endpoints.WinleafsServerEndpoint.SendRequest(String endpoint, Method method, Type returnType, Object body, Boolean disableLogging) in C:\Users\easy_\source\repos\winleafs\Winleafs\Winleafs.Server\Endpoints\WinleafsServerEndpoint.cs:line 120
   at Winleafs.Server.Endpoints.WinleafsServerEndpoint.SendRequest[T](String endpoint, Method method, Object body) in C:\Users\easy_\source\repos\winleafs\Winleafs\Winleafs.Server\Endpoints\WinleafsServerEndpoint.cs:line 43
   at Winleafs.Server.Endpoints.SpotifyEndpoint.IsConnected() in C:\Users\easy_\source\repos\winleafs\Winleafs\Winleafs.Server\Endpoints\SpotifyEndpoint.cs:line 36
   at Winleafs.Wpf.Views.Options.OptionsWindow.InitializeSpotifyButtons() in C:\Users\easy_\source\repos\winleafs\Winleafs\Winleafs.Wpf\Views\Options\OptionsWindow.xaml.cs:line 437
2023-09-05 13:19:06.1672|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request to Nanoleaf: Address: http://192.168.1.12:16021/, URL: api/v1/RebbMsWZs5KryF7Vm8sfRYHpcBxdh0yp/panelLayout/layout, Method: GET, Body: 
2023-09-05 13:19:06.1791|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request to Nanoleaf: Address: http://192.168.1.12:16021/, URL: api/v1/RebbMsWZs5KryF7Vm8sfRYHpcBxdh0yp/panelLayout/globalOrientation, Method: GET, Body: 
2023-09-05 13:19:06.1791|INFO|Winleafs.Wpf.Api.Orchestrator|Orchestrator is activating effect Winleafs - Screen mirror with brightness 0 for device 192.168.1.12
2023-09-05 13:19:06.1791|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request to Nanoleaf: Address: http://192.168.1.12:16021/, URL: api/v1/RebbMsWZs5KryF7Vm8sfRYHpcBxdh0yp/state, Method: PUT, Body: { brightness = { value = 0 } }
2023-09-05 13:19:06.3388|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request to Nanoleaf: Address: http://192.168.1.12:16021/, URL: api/v1/RebbMsWZs5KryF7Vm8sfRYHpcBxdh0yp/effects, Method: PUT, Body: { write = { command = display, animType = extControl, extControlVersion = v2 } }
2023-09-05 13:19:15.4291|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request to Nanoleaf: Address: http://192.168.1.12:16021/, URL: api/v1/RebbMsWZs5KryF7Vm8sfRYHpcBxdh0yp/panelLayout/layout, Method: GET, Body: 
2023-09-05 13:19:15.5309|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request to Nanoleaf: Address: http://192.168.1.12:16021/, URL: api/v1/RebbMsWZs5KryF7Vm8sfRYHpcBxdh0yp/panelLayout/globalOrientation, Method: GET, Body: 
2023-09-05 13:19:15.6078|INFO|Winleafs.Wpf.Api.ScheduleTimer|Scheduler turning device 192.168.1.12 off
2023-09-05 13:19:15.6078|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request to Nanoleaf: Address: http://192.168.1.12:16021/, URL: api/v1/RebbMsWZs5KryF7Vm8sfRYHpcBxdh0yp/state/on, Method: GET, Body: 
2023-09-05 13:19:15.6277|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request to Nanoleaf: Address: http://192.168.1.12:16021/, URL: api/v1/RebbMsWZs5KryF7Vm8sfRYHpcBxdh0yp/state, Method: PUT, Body: { on = { value = False } }
2023-09-05 13:19:20.1345|INFO|Winleafs.Wpf.Views.MainWindows.DeviceUserControl|User manually enabling effect Winleafs - Screen mirror with brightness 0 for device 192.168.1.12
2023-09-05 13:19:20.1345|INFO|Winleafs.Wpf.Api.Orchestrator|Orchestrator is activating effect Winleafs - Screen mirror with brightness 0 for device 192.168.1.12
2023-09-05 13:19:20.1345|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request to Nanoleaf: Address: http://192.168.1.12:16021/, URL: api/v1/RebbMsWZs5KryF7Vm8sfRYHpcBxdh0yp/state, Method: PUT, Body: { brightness = { value = 0 } }
2023-09-05 13:19:20.1969|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request to Nanoleaf: Address: http://192.168.1.12:16021/, URL: api/v1/RebbMsWZs5KryF7Vm8sfRYHpcBxdh0yp/effects, Method: PUT, Body: { write = { command = display, animType = extControl, extControlVersion = v2 } }
2023-09-05 13:19:24.9063|INFO|Winleafs.Server.Endpoints.WinleafsServerEndpoint|Sending following request Winleafs Server: Address: https://api.winleafs.com/, URL: /spotify/is-connected/5d3ff693-4894-45ea-bebf-ed1c2e557289, Method: GET, Body: 
2023-09-05 13:19:26.9186|WARN|Winleafs.Server.Endpoints.WinleafsServerEndpoint|Winleafs server request failed, statuscode: 0 0, status description: , content: 
2023-09-05 13:19:26.9186|ERROR|Winleafs.Wpf.Views.Options.OptionsWindow|Unknown error when trying to connect to Spotify
Winleafs.Server.Exceptions.WinleafsServerException: Error during request to Winleafs server
   at Winleafs.Server.Endpoints.WinleafsServerEndpoint.SendRequest(String endpoint, Method method, Type returnType, Object body, Boolean disableLogging) in C:\Users\easy_\source\repos\winleafs\Winleafs\Winleafs.Server\Endpoints\WinleafsServerEndpoint.cs:line 120
   at Winleafs.Server.Endpoints.WinleafsServerEndpoint.SendRequest[T](String endpoint, Method method, Object body) in C:\Users\easy_\source\repos\winleafs\Winleafs\Winleafs.Server\Endpoints\WinleafsServerEndpoint.cs:line 43
   at Winleafs.Server.Endpoints.SpotifyEndpoint.IsConnected() in C:\Users\easy_\source\repos\winleafs\Winleafs\Winleafs.Server\Endpoints\SpotifyEndpoint.cs:line 36
   at Winleafs.Wpf.Views.Options.OptionsWindow.InitializeSpotifyButtons() in C:\Users\easy_\source\repos\winleafs\Winleafs\Winleafs.Wpf\Views\Options\OptionsWindow.xaml.cs:line 437
2023-09-05 13:19:35.7307|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request to Nanoleaf: Address: http://192.168.1.12:16021/, URL: api/v1/RebbMsWZs5KryF7Vm8sfRYHpcBxdh0yp/panelLayout/layout, Method: GET, Body: 
2023-09-05 13:19:35.7600|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request to Nanoleaf: Address: http://192.168.1.12:16021/, URL: api/v1/RebbMsWZs5KryF7Vm8sfRYHpcBxdh0yp/panelLayout/globalOrientation, Method: GET, Body: 
2023-09-05 13:19:35.8386|INFO|Winleafs.Wpf.Api.Orchestrator|Orchestrator is activating effect Winleafs - Screen mirror with brightness 0 for device 192.168.1.12
2023-09-05 13:19:35.8386|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request to Nanoleaf: Address: http://192.168.1.12:16021/, URL: api/v1/RebbMsWZs5KryF7Vm8sfRYHpcBxdh0yp/state, Method: PUT, Body: { brightness = { value = 0 } }
2023-09-05 13:19:39.2514|INFO|Winleafs.Server.Endpoints.WinleafsServerEndpoint|Sending following request Winleafs Server: Address: https://api.winleafs.com/, URL: /spotify/is-connected/5d3ff693-4894-45ea-bebf-ed1c2e557289, Method: GET, Body: 
2023-09-05 13:19:41.2637|WARN|Winleafs.Server.Endpoints.WinleafsServerEndpoint|Winleafs server request failed, statuscode: 0 0, status description: , content: 
2023-09-05 13:19:41.2637|ERROR|Winleafs.Wpf.Views.Options.OptionsWindow|Unknown error when trying to connect to Spotify
Winleafs.Server.Exceptions.WinleafsServerException: Error during request to Winleafs server
   at Winleafs.Server.Endpoints.WinleafsServerEndpoint.SendRequest(String endpoint, Method method, Type returnType, Object body, Boolean disableLogging) in C:\Users\easy_\source\repos\winleafs\Winleafs\Winleafs.Server\Endpoints\WinleafsServerEndpoint.cs:line 120
   at Winleafs.Server.Endpoints.WinleafsServerEndpoint.SendRequest[T](String endpoint, Method method, Object body) in C:\Users\easy_\source\repos\winleafs\Winleafs\Winleafs.Server\Endpoints\WinleafsServerEndpoint.cs:line 43
   at Winleafs.Server.Endpoints.SpotifyEndpoint.IsConnected() in C:\Users\easy_\source\repos\winleafs\Winleafs\Winleafs.Server\Endpoints\SpotifyEndpoint.cs:line 36
   at Winleafs.Wpf.Views.Options.OptionsWindow.InitializeSpotifyButtons() in C:\Users\easy_\source\repos\winleafs\Winleafs\Winleafs.Wpf\Views\Options\OptionsWindow.xaml.cs:line 437
2023-09-05 13:19:49.7949|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request to Nanoleaf: Address: http://192.168.1.12:16021/, URL: api/v1/RebbMsWZs5KryF7Vm8sfRYHpcBxdh0yp/panelLayout/layout, Method: GET, Body: 
2023-09-05 13:19:49.8030|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request to Nanoleaf: Address: http://192.168.1.12:16021/, URL: api/v1/RebbMsWZs5KryF7Vm8sfRYHpcBxdh0yp/panelLayout/globalOrientation, Method: GET, Body: 
2023-09-05 13:19:49.8030|INFO|Winleafs.Wpf.Api.Orchestrator|Orchestrator is activating effect Winleafs - Screen mirror with brightness 0 for device 192.168.1.12
2023-09-05 13:19:49.8030|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request to Nanoleaf: Address: http://192.168.1.12:16021/, URL: api/v1/RebbMsWZs5KryF7Vm8sfRYHpcBxdh0yp/state, Method: PUT, Body: { brightness = { value = 0 } }
2023-09-05 13:19:49.8784|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request to Nanoleaf: Address: http://192.168.1.12:16021/, URL: api/v1/RebbMsWZs5KryF7Vm8sfRYHpcBxdh0yp/effects, Method: PUT, Body: { write = { command = display, animType = extControl, extControlVersion = v2 } }
2023-09-05 13:20:01.5859|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request to Nanoleaf: Address: http://192.168.1.12:16021/, URL: api/v1/RebbMsWZs5KryF7Vm8sfRYHpcBxdh0yp/panelLayout/layout, Method: GET, Body: 
2023-09-05 13:20:01.6545|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request to Nanoleaf: Address: http://192.168.1.12:16021/, URL: api/v1/RebbMsWZs5KryF7Vm8sfRYHpcBxdh0yp/panelLayout/globalOrientation, Method: GET, Body: 
2023-09-05 13:20:01.6887|INFO|Winleafs.Wpf.Api.ScheduleTimer|Scheduler turning device 192.168.1.12 off
2023-09-05 13:20:01.6887|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request to Nanoleaf: Address: http://192.168.1.12:16021/, URL: api/v1/RebbMsWZs5KryF7Vm8sfRYHpcBxdh0yp/state/on, Method: GET, Body: 
2023-09-05 13:20:01.7037|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request to Nanoleaf: Address: http://192.168.1.12:16021/, URL: api/v1/RebbMsWZs5KryF7Vm8sfRYHpcBxdh0yp/state, Method: PUT, Body: { on = { value = False } }
2023-09-05 13:20:04.7379|INFO|Winleafs.Wpf.Views.MainWindows.DeviceUserControl|User manually enabling effect Winleafs - Screen mirror with brightness 0 for device 192.168.1.12
2023-09-05 13:20:04.7379|INFO|Winleafs.Wpf.Api.Orchestrator|Orchestrator is activating effect Winleafs - Screen mirror with brightness 0 for device 192.168.1.12
2023-09-05 13:20:04.7379|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request to Nanoleaf: Address: http://192.168.1.12:16021/, URL: api/v1/RebbMsWZs5KryF7Vm8sfRYHpcBxdh0yp/state, Method: PUT, Body: { brightness = { value = 0 } }
2023-09-05 13:20:04.7876|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request to Nanoleaf: Address: http://192.168.1.12:16021/, URL: api/v1/RebbMsWZs5KryF7Vm8sfRYHpcBxdh0yp/effects, Method: PUT, Body: { write = { command = display, animType = extControl, extControlVersion = v2 } }
2023-09-05 13:21:02.3963|INFO|Winleafs.Server.Endpoints.WinleafsServerEndpoint|Sending following request Winleafs Server: Address: https://api.winleafs.com/, URL: /spotify/is-connected/5d3ff693-4894-45ea-bebf-ed1c2e557289, Method: GET, Body: 
2023-09-05 13:21:04.4112|WARN|Winleafs.Server.Endpoints.WinleafsServerEndpoint|Winleafs server request failed, statuscode: 0 0, status description: , content: 
2023-09-05 13:21:04.4112|ERROR|Winleafs.Wpf.Views.Options.OptionsWindow|Unknown error when trying to connect to Spotify
Winleafs.Server.Exceptions.WinleafsServerException: Error during request to Winleafs server
   at Winleafs.Server.Endpoints.WinleafsServerEndpoint.SendRequest(String endpoint, Method method, Type returnType, Object body, Boolean disableLogging) in C:\Users\easy_\source\repos\winleafs\Winleafs\Winleafs.Server\Endpoints\WinleafsServerEndpoint.cs:line 120
   at Winleafs.Server.Endpoints.WinleafsServerEndpoint.SendRequest[T](String endpoint, Method method, Object body) in C:\Users\easy_\source\repos\winleafs\Winleafs\Winleafs.Server\Endpoints\WinleafsServerEndpoint.cs:line 43
   at Winleafs.Server.Endpoints.SpotifyEndpoint.IsConnected() in C:\Users\easy_\source\repos\winleafs\Winleafs\Winleafs.Server\Endpoints\SpotifyEndpoint.cs:line 36
   at Winleafs.Wpf.Views.Options.OptionsWindow.InitializeSpotifyButtons() in C:\Users\easy_\source\repos\winleafs\Winleafs\Winleafs.Wpf\Views\Options\OptionsWindow.xaml.cs:line 437

**Comment by AoKoori** [comment]
after some research the issue was thaat my nanoleaf firmware wasn't up to date.
